apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-drupal-secret
type: Opaque
data:
  db-password: {{ .Values.database.password | b64enc }}
  {{- if .Values.smtp.enabled }}
  smtp-username: {{ .Values.smtp.username | b64enc }}
  smtp-password: {{ .Values.smtp.password | b64enc }}
  {{- end }}